repos:
  - repo: local
    hooks:
      - id: ruff-fix
        name: Ruff fix
        entry: ruff check --fix .
        language: system
        pass_filenames: false

      - id: ruff-format
        name: Ruff format
        entry: ruff format .
        language: system
        pass_filenames: false
