name: Linter and Formatter

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
